### ISSUE TITLE
installing wrong CMake config file

### ISSUE THREAD

**Issue by dirk-thomas** [plasmodic/ecto_ros#16]
The custom logic (https://github.com/plasmodic/ecto_ros/blob/7e9d33c8172f0a2197c2976ac566249ef7653af8/cmake/CMakeLists.txt#L9) installs the generated CMake config file for the *devel* space. This overwrites the CMake config file specifically generated for the install space.

An example of a failing job: http://54.183.26.131:8080/job/Ibin_arm_uThf__object_recognition_ros__ubuntu_trusty_armhf__binary/3/consoleFull#console-section-11

**Comment by stonier** [comment]
Looks like these could now be bundled as a CONFIG_EXTRAS cmake files and the install rule dropped for everything except the python script. Thanks for the heads up Dirk.

**Comment by vrabaud** [comment]
yop. Remember that ecto was the birth place of catkin :) https://github.com/plasmodic/ecto/commit/e919e9f8ccf383678ee5c4f602c9b2324b312721
Will fix that asap. What is that farm btw ? dockers based, arm, when will it replace the official one !?

**Comment by dirk-thomas** [comment]
Yes, that is the test farm using the new Docker - based stuff: http://wiki.ros.org/buildfarm

It currently lacks doc jobs. As soon as they work reliable we will replace the Indigo and Jade farm. Hopefully within a month...

**Comment by dirk-thomas** [comment]
The interesting thing is that this issue only appeared in the ARM build. I assume it is non-deterministic which install rule wins.

**Comment by vrabaud** [comment]
I hope you'll optimize that farm. 7 hours to build ecto_ros ...... I believe it's doing an apt-get update between the install of each dependency.

**Comment by dirk-thomas** [comment]
Building in Docker is slower than than on the host system. And using qemu to build arm is slowing it down significantly more.

Anyway seven hours is not normal. I have optimized the Docker base images since that build to be much faster especially when using apt (https://github.com/osrf/ubuntu_armhf-docker/commit/d2bb5c5db9ed819b432d995d523c3c1d56599076).

But running update before install is the "right" thing to do in Docker files (see https://docs.docker.com/articles/dockerfile_best-practices/#the-dockerfile-instructions for a detailed description why).

**Comment by dirk-thomas** [comment]
I can confirm that the previously failing job is not building successfully: http://54.183.26.131:8080/job/Ibin_arm_uThf__object_recognition_ros__ubuntu_trusty_armhf__binary/4/

**Comment by vrabaud** [comment]
*now you mean :)
For the 7 hours, this code is highly templated.

Anyway, for apt-get, as mentioned by your doc actually:

    RUN apt-get update && apt-get install -y package-bar package-foo package-baz

you should not do:

    RUN echo "ros-indigo-object-recognition-core: 0.6.4-0trusty" && python3 -u /tmp/wrapper_scripts/apt-get.py update-and-install -q -y ros-indigo-object-recognition-core

and then

    RUN echo "ros-indigo-object-recognition-msgs: 0.4.1-0trusty" && python3 -u /tmp/wrapper_scripts/apt-get.py update-and-install -q -y ros-indigo-object-recognition-msgs

But somehow, something like:

    RUN echo "ros-indigo-object-recognition-core: 0.6.4-0trusty, ros-indigo-object-recognition-msgs: 0.4.1-0trusty" && python3 -u /tmp/wrapper_scripts/apt-get.py update-and-install -q -y ros-indigo-object-recognition-core ros-indigo-object-recognition-msgs

Not sure if your script supports that, but it should. According to your logs, you would gain 40s per dependency .......

**Comment by dirk-thomas** [comment]
If the Dockerfiles would install all dependencies in a single line that would also prevent other jobs with partly overlapping dependencies to reuse any of the in-between images.

**Comment by dirk-thomas** [comment]
Actually the latest job of `ecto_ros` took "only 35 minutes for apt-get update & install. The majority of the time (6h) is spent on compiling with qemu. I don't think there is much we can do to improve this.

**Comment by stonier** [comment]
> (6h) is spent on compiling with qemu. I don't think there is much we can do to improve this

Absolutely - I've spent weeks with qemu builds before. The only way to be fast is to cross-compile, but you don't want to do that outside of a minimal set of packages that you control otherwise you introduce a host of build configuration problems. Gentoo crossdev, yocto, openembedded all try this, but it's hard work to deliver a fully working chain of packages and get fixes upstream. Alot of manpower required.

@dirk-thomas I imagine you talked about going this route with people. Are these problems why you are doing qemu?

**Comment by dirk-thomas** [comment]
May be @trainman419 can comment on this. He did the original push for ARM and I integrated his approach into the new build farm.

The current qemu-based approach gets us through more than 80% of Indigo packages (even if it is a bit slow). More should be possible once we have pcl for arm.

**Comment by stonier** [comment]
80% is an awesome number. That justifies qemu totally. It would have been far harder to handle it any other way.

**Comment by trainman419** [comment]
I've tried to get cross-compile builds going a few times, and always failed. The qemu builds are slow, but they're reliable, and I'm completely willing to trade CPU time for my sanity.
