### ISSUE TITLE
Commit/revert

### ISSUE THREAD

**Issue by stonier** [plasmodic/ecto_ros#18]
@vrabaud 

Accidentally got my git push pointer confused between my remote and this one. End result, I pushed two fixes directly here.

I've reverted these, but they are filling up the history needlessly now. Do you want to reset back to the hash prior to these two commits or shall I just make pull requests for these two fixes on top of these reverts?

Apologies :confused:

**Comment by vrabaud** [comment]
well, just reset, I doubt people are upadting there sources every day on ecto

**Comment by stonier** [comment]
Done...PR's in.
